### ISSUE TITLE
Incompatible with Python 2

### ISSUE THREAD

**Issue by tkdchen** [misli/django-fas#4]
setup.py declares that this package works with Python 2 at line https://github.com/misli/django-fas/blob/master/setup.py#L27,
but `FasBackend.authenticate`[1] has invalid syntax for Python 2.

[1] https://github.com/misli/django-fas/blob/master/fas/backend.py#L10

**Comment by misli** [comment]
Since upcoming end-of-life of Python 2, I'd fix it removing the line from setup.py. Is that OK?

**Comment by tkdchen** [comment]
Sure. Thanks.
